# Homebrew
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
brew "brew-cask-completion"

# Fonts
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-mononoki-nerd-font"

# Terminal
cask "iterm2"

# Shell
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "zsh"
brew "zsh-completions"

# GNU Tools
brew "coreutils"
brew "binutils"
brew "diffutils"
brew "findutils"
brew "gawk"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "gnutls"
brew "grep"
brew "gzip"
brew "less"
brew "make"
brew "screen"

# Docker / Kubernetes
cask "docker"
brew "docker-completion"
brew "docker-compose-completion"
brew "kubernetes-cli"
brew "helm"
brew "kustomize"
brew "kubectx"
brew "stern"
brew "minikube"

# Browsers
cask "firefox"
cask "google-chrome"
cask "brave-browser"

# Source Control & Editors
brew "git"
brew "vim"
cask "visual-studio-code"

# CLI Tools
brew "tmux"
brew "fzf"
brew "cfssl"
brew "archey"
brew "cowsay"
brew "fortune"
brew "cowsay"
brew "lolcat"
brew "bat"
brew "glances"
brew "htop"
brew "nmap"
brew "prettyping"
brew "tree"
brew "watch"
brew "wdiff"
brew "wget"
brew "jq"
brew "yq"
brew "tldr"
brew "speedtest-cli"

# Apps
cask "appcleaner"
cask "keepingyouawake"
cask "rectangle"
cask "1password-beta"
cask "1password-cli"
cask "spotify"
cask "slack"
cask "google-backup-and-sync"
cask "nordvpn"
cask "transmission"
cask "vlc"
cask "vagrant"
brew "vagrant-completion"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "zoom"
